apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-gateway
  namespace: ngrok-ingress-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-gateway
  template:
    metadata:
      labels:
        app: nginx-gateway
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: nginx-config-volume
              mountPath: /etc/nginx/conf.d/
      volumes:
        - name: nginx-config-volume
          configMap:
            name: nginx-config
            items: 
             - key: default.conf
               path: default.conf
