apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: ngrok-ingress-controller
spec:
  selector:
    app: nginx-gateway
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
