apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: ngrok-ingress-controller
data:
  conf.d: |
    # Custom NGINX configuration for the gateway
    server {
      listen 80;
      server_name localhost;
      
      location /game {
        proxy_pass http://game-2048.iot-app.svc.cluster.local;
        proxy_set_header Host $host
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwareder-For $proxy_add_x_forwarded_for;
      }
      
      location /argo {
        proxy_pass http://argocd-server.argocd.svc.cluster.local:443;
      }
      
    }
