apiVersion: apps/v1
kind: Deployment
metadata:
  name: homeassistant
  namespace: iot-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homeassistant
  template:
    metadata:
      labels:
        app: homeassistant
    spec:
      containers:
        - name: homeassistant
          image: homeassistant/home-assistant
          ports:
            - name: http
              containerPort: 8123
