apiVersion: v1
kind: Service
metadata:
  name: homeassistant
  namespace: iot-app
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8123
    - name: https
      protocol: TCP
      port: 443
      targetPort: 8123
  selector:
    app: homeassistant