apiVersion: v1
kind: Secret
metadata:
  name: homeassist-config
type: Opaque
data:
  configuration.yaml: ZGVmYXVsdF9jb25maWc6CgpodHRwOgogIHVzZV94X2ZvcndhcmRlZF9mb3I6IHRydWUKICB0cnVzdGVkX3Byb3hpZXM6CiAgICAtIDEwLjI0NC4xLjY4
