name: Docker Image CI for GHCR

on:
  push:
    tags:
    - '*'

jobs:
  build_and_publish:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the image
        run : |
          docker login --username darking2539 --password ${{ secrets.GH_PAT }} ghcr.io
          docker build ./client --tag ghcr.io/darking2539/iot-app-client:latest
          docker build ./server --tag ghcr.io/darking2539/iot-app-server:latest
          docker push ghcr.io/darking2539/iot-app-client:latest
          docker push ghcr.io/darking2539/iot-app-server:latest